version: '3.4'

services:
  dnsmasq-proxy:
    image: linkat/dnsmasq-fog:1.0.0
    container_name: dnsmasq-fog
    environment:
      - TFTP_SERVER_IP=192.168.1.225
    cap_add:
      - NET_ADMIN
#    network_mode: host
    ports:
      - 67:67
      - 4011:4011
    restart: always
